[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
optimizer = true
optimizer_runs = 200
solc = '0.8.20'
evm_version = 'shanghai'
bytecode_hash = 'none'
ignored_warnings_from = ["src/periphery/contracts/treasury/RevenueSplitter.sol"]
out = 'out'
libs = ['lib']
remappings = []
fs_permissions = [
    { access = "write", path = "./reports" },
    { access = "read", path = "./out" },
    { access = "read", path = "./config" },
]
ffi = true

[fuzz]
runs = 1000
max_test_rejects = 400000
